image: nixos/nix
pages:
  script:
    # the final contents for your page always have to be stored in the public folder
    - nix build --experimental-features 'nix-command flakes'
    - cp -r result/. public/
  artifacts:
    # artifact to make it visible for gitlab pages
    paths:
      - public
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH